### ISSUE TITLE
pgsql binding won't build with postgresql 8.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ClosestStorm/v8cgi#62]
```
Several places, TRUE should be true and FALSE should be false in pgsql.cc

postgresql_fe.h should not be included.

src/lib/pgsql/pgsql.cc:957: error: `pg_encoding_to_char' undeclared in 
   namespace `pgsql::pq'

-- the function isn't available in postgresql 8.2
```

Original issue reported on code.google.com by `aredridel` on 11 Mar 2010 at 6:35
